filename: ci/cloudbuild/cloudbuild.yaml
github:
  name: functions-framework-cpp
  owner: GoogleCloudPlatform
  pullRequest:
    branch: ^(master|main|v\d+\..*)$
    commentControl: COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY
name: check-api-pr
substitutions:
  _BUILD_NAME: check-api
  _DISTRO: fedora-34
  _TRIGGER_TYPE: pr
includeBuildLogs: INCLUDE_BUILD_LOGS_WITH_STATUS
tags:
- pr
