filename: ci/cloudbuild/cloudbuild.yaml
github:
  name: functions-framework-cpp
  owner: GoogleCloudPlatform
  push:
    branch: ^(main|v\d+\..*)$
name: clang-tidy-ci
substitutions:
  _BUILD_NAME: clang-tidy
  _DISTRO: fedora-38
  _TRIGGER_TYPE: ci
includeBuildLogs: INCLUDE_BUILD_LOGS_WITH_STATUS
tags:
- ci
