filename: ci/cloudbuild/cloudbuild.yaml
github:
  name: functions-framework-cpp
  owner: GoogleCloudPlatform
  pullRequest:
    branch: ^(main|v\d+\..*)$
    commentControl: COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY
name: sanitize-address-pr
substitutions:
  _BUILD_NAME: sanitize-address
  _DISTRO: fedora-38
  _TRIGGER_TYPE: pr
includeBuildLogs: INCLUDE_BUILD_LOGS_WITH_STATUS
tags:
- pr
