name: build-framework

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-ubuntu:
    name: Compile the Framework and Run Unit tests
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install-deps
      run: vcpkg install gtest
    - name: configure
      run: cmake -S . -B ${{runner.workspace}}/build -DCMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake
    - name: build
      run: cmake --build ${{runner.workspace}}/build
    - name: test
      working-directory: ${{runner.workspace}}/build
      run: ctest
