name: build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-ubuntu-focal:
    name: ubuntu-20.04
    runs-on: ubuntu-20.04
    steps:
    - name: install ninja
      run: sudo apt install ninja-build
    - uses: actions/checkout@v2
    - name: cache-vcpkg
      id: cache-vcpkg
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/vcpkg
        key: vcpkg-${{ runner.os }}-${{ github.job }}-${{ hashFiles('vcpkg.json') }}
    - name: debug1
      run: type ninja
    - name: debug2
      run: ls -l /usr/bin/ninja
    - name: debug3
      run: ninja --version
    - name: debug4
      run: cmake --help
    - name: debug5
      run: type vcpkg
    - name: configure
      run: >
        cmake -S . -B ${{runner.workspace}}/build -GNinja
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        -DCMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake
    - name: build
      run: cmake --build ${{runner.workspace}}/build
    - name: test
      working-directory: ${{runner.workspace}}/build
      run: ctest
