name: C++ Unit CI

on:
  push:
    branches: [ main ]
  pull_request:

env:
  vcpkg_SHA: "65e5ea1df685a5362e70367bef4dbf827addff31"

jobs:

  msvc-2019:
    # Using a blank name produces better output on
    # the web UI (e.g. "sanitize /  (address)") than
    # any other alternative we tried.
    name: msvc-2019
    runs-on: windows-2019
    strategy:
      matrix:
        triplet: ["x64-windows"]
    steps:
      - uses: actions/checkout@v2
      - name: clone-vcpkg
        working-directory: "${{runner.temp}}"
        shell: powershell
        run: |
          $ErrorActionPreference = "Stop"
          Write-Host -ForegroundColor Yellow "`n$(Get-Date -Format o) downloading:"
          (New-Object System.Net.WebClient).Downloadfile( `
              'https://github.com/microsoft/vcpkg/archive/${{env.vcpkg_SHA}}.zip', `
              '${{env.vcpkg_SHA}}.zip')
          Write-Host -ForegroundColor Yellow "`n$(Get-Date -Format o) done:"
          dir .
          Write-Host -ForegroundColor Yellow "`n$(Get-Date -Format o) extrating:"
          &7z x -r -ovcpkg ${{env.vcpkg_SHA}}.zip
          if ($LastExitCode -ne 0) { throw "7z failed with exit code $LastExitCode"; }
          Write-Host -ForegroundColor Yellow "`n$(Get-Date -Format o) done:"
          dir .
          Write-Host -ForegroundColor Yellow "`n$(Get-Date -Format o) vcpkg contents:"
          dir vcpkg
          Write-Host -ForegroundColor Yellow "`n$(Get-Date -Format o) downloading exe:"
          (New-Object System.Net.WebClient).Downloadfile( `
                  'https://github.com/microsoft/vcpkg-tool/releases/download/2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35/vcpkg.exe', `
                  'vcpkg\vcpkg.exe')
          Write-Host -ForegroundColor Yellow "`n$(Get-Date -Format o) vcpkg contents:"
          dir vcpkg
      - name: cache-vcpkg
        id: cache-vcpkg
        uses: actions/cache@v2
        with:
          # Preserve the vcpkg binary *and* the vcpkg binary cache in the build cache
          path: |
            ~/AppData/vcpkg/archives
          key: |
            vcpkg-${{ env.vcpkg_SHA }}-msvc-2019-${{ matrix.triplet }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ env.vcpkg_SHA }}-msvc-2019-${{ matrix.triplet }}-
      - name: download-vcpkg
        run: |
          $ErrorActionPreference = "Stop"
      - name: triplet=${{matrix.triplet}} / configure
        shell: cmd
        run: |
          call "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          ${{runner.temp}}\vcpkg\vcpkg.exe install boost-core
#          cmake -S . -B "${{runner.temp}}/build" -GNinja `
#          -DCMAKE_BUILD_TYPE=Debug `
#          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON `
#          -DCMAKE_TARGET_TRIPLET="${{matrix.triplet}}" `
#          -DCMAKE_TOOLCHAIN_FILE="${{runner.temp}}/vcpkg/scripts/buildsystems/vcpkg.cmake" `
#      - name: triplet=${{matrix.triplet}} / build
#        run: cmake --build "${{runner.temp}}/build"
#      - name: triplet=${{matrix.triplet}} / test
#        working-directory: "${{runner.temp}}/build"
#        run: ctest --output-on-failure --timeout=60s -C Debug
