name: C++ Unit CI

on:
  push:
    branches: [ main ]
  pull_request:

env:
  vcpkg_SHA: "5214a247018b3bf2d793cea188ea2f2c150daddd"

jobs:
  build-ubuntu-focal:
    name: ubuntu-20.04
    runs-on: ubuntu-20.04
    steps:
    - name: install ninja
      run: sudo apt install ninja-build
    - uses: actions/checkout@v2
    - name: clone-vcpkg
      working-directory: "${{runner.temp}}"
      run: >
        mkdir -p vcpkg &&
        curl -sSL "https://github.com/microsoft/vcpkg/archive/${{env.vcpkg_SHA}}.tar.gz" |
        tar -C vcpkg --strip-components=1 -zxf -
    - name: cache-vcpkg
      id: cache-vcpkg
      uses: actions/cache@v2
      with:
        # Preserve the vcpkg binary *and* the vcpkg binary cache in the build cache
        path: |
          ~/.cache/vcpkg
          ~/.cache/bin
        key: |
          vcpkg-${{ env.vcpkg_SHA }}-build-ubuntu-focal-${{ hashFiles('vcpkg.json') }}
        restore-keys: |
          vcpkg-${{ env.vcpkg_SHA }}-build-ubuntu-focal-
    - name: boostrap-vcpkg
      run: ci/restore-vcpkg-from-cache.sh "${{runner.temp}}/vcpkg"

    - name: configure
      run: >
        cmake -S . -B "${{runner.temp}}/build" -GNinja
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        -DCMAKE_TOOLCHAIN_FILE="${{runner.temp}}/vcpkg/scripts/buildsystems/vcpkg.cmake"
    - name: build
      run: cmake --build "${{runner.temp}}/build"
    - name: test
      working-directory: "${{runner.temp}}/build"
      run: ctest --output-on-failure --timeout=60s
