name: C++ Conformance CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-22.04
    steps:
    - name: apt-install
      run: |
        sudo apt install ninja-build lcov \
          libboost-dev libboost-program-options-dev libboost-filesystem-dev \
          nlohmann-json3-dev libabsl-dev libgtest-dev libgmock-dev
    - name: build-gtest
      run: |
        sudo cmake -G Ninja -S /usr/src/googletest -B /var/tmp/build/gtest
        sudo cmake --build /var/tmp/build/gtest
        sudo cmake --install /var/tmp/build/gtest
    - uses: actions/checkout@v2
    - name: configure
      run: |
        cmake -G Ninja -S . -B ${{runner.workspace}}/build \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_CXX_FLAGS=--coverage \
          -DFUNCTIONS_FRAMEWORK_CPP_TEST_EXAMPLES=OFF
    - name: build
      run: cmake --build ${{runner.workspace}}/build
    - name: test
      working-directory: ${{runner.workspace}}/build
      run: ctest --output-on-failure --timeout=60s

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16'

    - name: Run Cloud Event conformance tests
      uses: GoogleCloudPlatform/functions-framework-conformance/action@v1.8.3
      with:
        functionType: 'cloudevent'
        useBuildpacks: false
        validateMapping: true
        cmd: '${{runner.workspace}}/build/google/cloud/functions/integration_tests/cloud_event_conformance'

    - name: Run HTTP conformance tests
      uses: GoogleCloudPlatform/functions-framework-conformance/action@v1.8.3
      with:
        functionType: 'http'
        useBuildpacks: false
        validateMapping: true
        cmd: '${{runner.workspace}}/build/google/cloud/functions/integration_tests/http_conformance'

    - name: coverage-upload
      uses: codecov/codecov-action@v3
      with:
        gcov: true
