name: images

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  images:
    name: images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup-buildx
        uses: docker/setup-buildx-action@v1

      - name: docker-cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ runner.os }}-images-${{ github.sha }}
          restore-keys: |
            buildx-${{ runner.os }}-images-

      - name: docker-build-runtime
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          tags: gcf-cpp-runtime
          context: build_scripts
          file: build_scripts/Dockerfile
          target: gcf-cpp-runtime
          cache-from: type=local,src=/tmp/.buildx-cache/runtime
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache/runtime

      - name: docker-build-develop
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          tags: gcf-cpp-develop
          context: build_scripts
          file: build_scripts/Dockerfile
          target: gcf-cpp-incremental-8
          cache-from: type=local,src=/tmp/.buildx-cache/develop
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache/develop
