name: sanitize

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  asan:
    name: Sanitize with -fsanitize-address
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: cache-vcpkg
        id: cache-vcpkg
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/vcpkg
          key: ${{ runner.os }}-vcpkg
      - name: install-deps
        run: vcpkg install gtest
      - name: configure
        run: >
          cmake -S . -B ${{runner.workspace}}/build
          -DCMAKE_CXX_COMPILER=clang++-10
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_CXX_FLAGS=-fsanitize-address
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          -DCMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake
      - name: build
        run: cmake --build ${{runner.workspace}}/build
      - name: test
        working-directory: ${{runner.workspace}}/build
        run: ctest
